export const FETCHED_EVENTS = 'FETCHED_EVENTS';

export const SELECTED_CURRENT_EVENT = 'SELECTED_CURRENT_EVENT';

export const FETCHED_EVENT_FILES = 'FETCHED_EVENT_FILES';

export const FILE_FINISHED_DOWNLOADING = 'FILE_FINISHED_DOWNLOADING';