export const FILE_FINISHED_DOWNLOADING = 'FILE_FINISHED_DOWNLOADING';

export const FETCHED_EVENT_FILES = 'FETCHED_EVENT_FILES';

export const REMOVE_FILE = 'REMOVE_FILE';

export const SET_DOWNLOAD_PROGRESS = 'SET_DOWNLOAD_PROGRESS';